name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build docs
        id: build_docs_first
        continue-on-error: true
        uses: TinyTapeout/tt-gds-action/docs@ttihp26b

      - name: Build docs (retry)
        if: steps.build_docs_first.outcome == 'failure'
        uses: TinyTapeout/tt-gds-action/docs@ttihp26b
